from qiskit.providers.models import BackendProperties, QasmBackendConfiguration
from qiskit_aer import AerSimulator
prop_dict = {   'backend_name': 'backend_3',
    'backend_version': '1.1.1',
    'gates': [   {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [0]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [1]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [2]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [3]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [4]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [5]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [6]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [7]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [8]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [9]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [10]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [11]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [12]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [13]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [14]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [0]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [1]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [2]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [3]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [4]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [5]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [6]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [7]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [8]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [9]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [10]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [11]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [12]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [13]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [14]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [0]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [1]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [2]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [3]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [4]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [5]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [6]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [7]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [8]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [9]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [10]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [11]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [12]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [13]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [14]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [0]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [1]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [2]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [3]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [4]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [5]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [6]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [7]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [8]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [9]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [10]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [11]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [12]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [13]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [14]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [0, 1]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [1, 0]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [0, 14]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [14, 0]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [0, 2]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [2, 0]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [0, 4]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [4, 0]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [1, 2]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [2, 1]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [1, 3]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [3, 1]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [1, 5]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [5, 1]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [2, 3]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [3, 2]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [2, 5]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [5, 2]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [3, 4]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [4, 3]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [3, 6]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [6, 3]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [4, 5]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [5, 4]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [4, 6]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [6, 4]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [5, 6]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [6, 5]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [6, 7]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [7, 6]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [7, 8]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [8, 7]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [7, 12]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [12, 7]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [8, 9]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [9, 8]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [8, 11]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [11, 8]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [8, 12]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [12, 8]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [9, 10]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [10, 9]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [10, 11]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [11, 10]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [11, 12]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [12, 11]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [11, 13]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [13, 11]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [12, 13]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [13, 12]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [13, 14]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.8195514056140689}],
                     'qubits': [14, 13]}],
    'general': [   {   'date': '2018-04-02 15:00:00Z',
                       'name': 'fridge_temperature',
                       'unit': 'mK',
                       'value': '10'}],
    'last_update_date': '2018-04-02 15:00:00Z',
    'qubits': [   [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}]]}
config_dict = {   'backend_name': 'backend_3',
    'backend_version': '1.1.1',
    'basis_gates': ['u1', 'u2', 'u3', 'rz', 'cx'],
    'conditional': 'true',
    'coupling_map': [   [0, 1],
                        [1, 0],
                        [0, 14],
                        [14, 0],
                        [0, 2],
                        [2, 0],
                        [0, 4],
                        [4, 0],
                        [1, 2],
                        [2, 1],
                        [1, 3],
                        [3, 1],
                        [1, 5],
                        [5, 1],
                        [2, 3],
                        [3, 2],
                        [2, 5],
                        [5, 2],
                        [3, 4],
                        [4, 3],
                        [3, 6],
                        [6, 3],
                        [4, 5],
                        [5, 4],
                        [4, 6],
                        [6, 4],
                        [5, 6],
                        [6, 5],
                        [6, 7],
                        [7, 6],
                        [7, 8],
                        [8, 7],
                        [7, 12],
                        [12, 7],
                        [8, 9],
                        [9, 8],
                        [8, 11],
                        [11, 8],
                        [8, 12],
                        [12, 8],
                        [9, 10],
                        [10, 9],
                        [10, 11],
                        [11, 10],
                        [11, 12],
                        [12, 11],
                        [11, 13],
                        [13, 11],
                        [12, 13],
                        [13, 12],
                        [13, 14],
                        [14, 13]],
    'description': 'A 15 qubit backend',
    'dt': 1.33,
    'dtm': 10.5,
    'gates': [   {   'coupling_map': [   [0],
                                         [1],
                                         [2],
                                         [3],
                                         [4],
                                         [5],
                                         [6],
                                         [7],
                                         [8],
                                         [9],
                                         [10],
                                         [11],
                                         [12],
                                         [13],
                                         [14]],
                     'name': 'u1',
                     'parameters': ['lambda'],
                     'qasm_def': 'gate u1(lambda) q { U(0,0,lambda) q; }'},
                 {   'coupling_map': [   [0],
                                         [1],
                                         [2],
                                         [3],
                                         [4],
                                         [5],
                                         [6],
                                         [7],
                                         [8],
                                         [9],
                                         [10],
                                         [11],
                                         [12],
                                         [13],
                                         [14]],
                     'name': 'u2',
                     'parameters': ['phi', 'lambda'],
                     'qasm_def': 'gate u2(phi,lambda) q { U(pi/2,phi,lambda) '
                                 'q; }'},
                 {   'coupling_map': [   [0],
                                         [1],
                                         [2],
                                         [3],
                                         [4],
                                         [5],
                                         [6],
                                         [7],
                                         [8],
                                         [9],
                                         [10],
                                         [11],
                                         [12],
                                         [13],
                                         [14]],
                     'name': 'u3',
                     'parameters': ['theta', 'phi', 'lambda'],
                     'qasm_def': 'u3(theta,phi,lambda) q { U(theta,phi,lambda) '
                                 'q; }'},
                 {   'coupling_map': [   [0],
                                         [1],
                                         [2],
                                         [3],
                                         [4],
                                         [5],
                                         [6],
                                         [7],
                                         [8],
                                         [9],
                                         [10],
                                         [11],
                                         [12],
                                         [13],
                                         [14]],
                     'name': 'rz',
                     'parameters': ['theta'],
                     'qasm_def': 'gate rz(theta) q { U(0, 0, theta) q; }'},
                 {   'coupling_map': [   [0, 1],
                                         [1, 0],
                                         [0, 14],
                                         [14, 0],
                                         [0, 2],
                                         [2, 0],
                                         [0, 4],
                                         [4, 0],
                                         [1, 2],
                                         [2, 1],
                                         [1, 3],
                                         [3, 1],
                                         [1, 5],
                                         [5, 1],
                                         [2, 3],
                                         [3, 2],
                                         [2, 5],
                                         [5, 2],
                                         [3, 4],
                                         [4, 3],
                                         [3, 6],
                                         [6, 3],
                                         [4, 5],
                                         [5, 4],
                                         [4, 6],
                                         [6, 4],
                                         [5, 6],
                                         [6, 5],
                                         [6, 7],
                                         [7, 6],
                                         [7, 8],
                                         [8, 7],
                                         [7, 12],
                                         [12, 7],
                                         [8, 9],
                                         [9, 8],
                                         [8, 11],
                                         [11, 8],
                                         [8, 12],
                                         [12, 8],
                                         [9, 10],
                                         [10, 9],
                                         [10, 11],
                                         [11, 10],
                                         [11, 12],
                                         [12, 11],
                                         [11, 13],
                                         [13, 11],
                                         [12, 13],
                                         [13, 12],
                                         [13, 14],
                                         [14, 13]],
                     'name': 'cx',
                     'parameters': [],
                     'qasm_def': 'gate cx q1,q2 { CX q1,q2; }'}],
    'local': 'true',
    'max_shots': 9000,
    'memory': 'true',
    'n_qubits': 15,
    'open_pulse': 'false',
    'simulator': 'true'}
backend = AerSimulator(properties=BackendProperties.from_dict(prop_dict), configuration=QasmBackendConfiguration.from_dict(config_dict), basis_gates=['u1','u2','u3','rz','cx'])