from qiskit.providers.models import BackendProperties, QasmBackendConfiguration
from qiskit_aer import AerSimulator
prop_dict = {   'backend_name': 'backend_17',
    'backend_version': '1.1.1',
    'gates': [   {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [0]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [1]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [2]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [3]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [4]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [5]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [6]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [7]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [8]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [9]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [10]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [11]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [12]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [13]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [14]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [15]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [16]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [17]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [18]},
                 {   'gate': 'u1',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [19]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [0]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [1]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [2]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [3]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [4]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [5]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [6]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [7]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [8]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [9]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [10]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [11]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [12]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [13]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [14]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [15]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [16]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [17]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [18]},
                 {   'gate': 'u2',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [19]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [0]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [1]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [2]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [3]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [4]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [5]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [6]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [7]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [8]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [9]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [10]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [11]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [12]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [13]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [14]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [15]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [16]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [17]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [18]},
                 {   'gate': 'u3',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [19]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [0]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [1]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [2]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [3]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [4]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [5]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [6]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [7]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [8]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [9]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [10]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [11]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [12]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [13]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [14]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [15]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [16]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [17]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [18]},
                 {   'gate': 'rz',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [19]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [0, 1]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [1, 0]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [0, 19]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [19, 0]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [0, 2]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [2, 0]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [0, 3]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [3, 0]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [1, 2]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [2, 1]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [1, 3]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [3, 1]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [1, 4]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [4, 1]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [2, 3]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [3, 2]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [2, 4]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [4, 2]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [3, 4]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [4, 3]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [4, 5]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [5, 4]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [5, 6]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [6, 5]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [5, 7]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [7, 5]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [5, 8]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [8, 5]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [6, 7]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [7, 6]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [6, 8]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [8, 6]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [6, 9]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [9, 6]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [7, 8]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [8, 7]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [7, 9]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [9, 7]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [8, 9]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [9, 8]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [9, 10]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [10, 9]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [10, 11]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [11, 10]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [10, 12]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [12, 10]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [10, 13]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [13, 10]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [11, 12]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [12, 11]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [11, 14]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [14, 11]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [11, 15]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [15, 11]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [12, 13]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [13, 12]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [12, 16]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [16, 12]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [13, 14]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [14, 13]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [13, 15]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [15, 13]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [14, 15]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [15, 14]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [14, 16]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [16, 14]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [15, 16]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [16, 15]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [16, 17]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [17, 16]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [17, 18]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [18, 17]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [17, 19]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [19, 17]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [18, 19]},
                 {   'gate': 'cx',
                     'parameters': [   {   'date': '2018-04-02 15:00:00Z',
                                           'name': 'gate_error',
                                           'unit': '',
                                           'value': 0.6128026182226978}],
                     'qubits': [19, 18]}],
    'general': [   {   'date': '2018-04-02 15:00:00Z',
                       'name': 'fridge_temperature',
                       'unit': 'mK',
                       'value': '10'}],
    'last_update_date': '2018-04-02 15:00:00Z',
    'qubits': [   [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}],
                  [   {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T1',
                          'unit': 'us',
                          'value': 658252.883975393},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'T2',
                          'unit': 'us',
                          'value': 522605.155233436},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_error',
                          'unit': '',
                          'value': 0.08047339131740648},
                      {   'date': '2018-04-02 15:00:00Z',
                          'name': 'readout_length',
                          'unit': 'ns',
                          'value': 30}]]}
config_dict = {   'backend_name': 'backend_17',
    'backend_version': '1.1.1',
    'basis_gates': ['u1', 'u2', 'u3', 'rz', 'cx'],
    'conditional': 'true',
    'coupling_map': [   [0, 1],
                        [1, 0],
                        [0, 19],
                        [19, 0],
                        [0, 2],
                        [2, 0],
                        [0, 3],
                        [3, 0],
                        [1, 2],
                        [2, 1],
                        [1, 3],
                        [3, 1],
                        [1, 4],
                        [4, 1],
                        [2, 3],
                        [3, 2],
                        [2, 4],
                        [4, 2],
                        [3, 4],
                        [4, 3],
                        [4, 5],
                        [5, 4],
                        [5, 6],
                        [6, 5],
                        [5, 7],
                        [7, 5],
                        [5, 8],
                        [8, 5],
                        [6, 7],
                        [7, 6],
                        [6, 8],
                        [8, 6],
                        [6, 9],
                        [9, 6],
                        [7, 8],
                        [8, 7],
                        [7, 9],
                        [9, 7],
                        [8, 9],
                        [9, 8],
                        [9, 10],
                        [10, 9],
                        [10, 11],
                        [11, 10],
                        [10, 12],
                        [12, 10],
                        [10, 13],
                        [13, 10],
                        [11, 12],
                        [12, 11],
                        [11, 14],
                        [14, 11],
                        [11, 15],
                        [15, 11],
                        [12, 13],
                        [13, 12],
                        [12, 16],
                        [16, 12],
                        [13, 14],
                        [14, 13],
                        [13, 15],
                        [15, 13],
                        [14, 15],
                        [15, 14],
                        [14, 16],
                        [16, 14],
                        [15, 16],
                        [16, 15],
                        [16, 17],
                        [17, 16],
                        [17, 18],
                        [18, 17],
                        [17, 19],
                        [19, 17],
                        [18, 19],
                        [19, 18]],
    'description': 'A 20 qubit backend',
    'dt': 1.33,
    'dtm': 10.5,
    'gates': [   {   'coupling_map': [   [0],
                                         [1],
                                         [2],
                                         [3],
                                         [4],
                                         [5],
                                         [6],
                                         [7],
                                         [8],
                                         [9],
                                         [10],
                                         [11],
                                         [12],
                                         [13],
                                         [14],
                                         [15],
                                         [16],
                                         [17],
                                         [18],
                                         [19]],
                     'name': 'u1',
                     'parameters': ['lambda'],
                     'qasm_def': 'gate u1(lambda) q { U(0,0,lambda) q; }'},
                 {   'coupling_map': [   [0],
                                         [1],
                                         [2],
                                         [3],
                                         [4],
                                         [5],
                                         [6],
                                         [7],
                                         [8],
                                         [9],
                                         [10],
                                         [11],
                                         [12],
                                         [13],
                                         [14],
                                         [15],
                                         [16],
                                         [17],
                                         [18],
                                         [19]],
                     'name': 'u2',
                     'parameters': ['phi', 'lambda'],
                     'qasm_def': 'gate u2(phi,lambda) q { U(pi/2,phi,lambda) '
                                 'q; }'},
                 {   'coupling_map': [   [0],
                                         [1],
                                         [2],
                                         [3],
                                         [4],
                                         [5],
                                         [6],
                                         [7],
                                         [8],
                                         [9],
                                         [10],
                                         [11],
                                         [12],
                                         [13],
                                         [14],
                                         [15],
                                         [16],
                                         [17],
                                         [18],
                                         [19]],
                     'name': 'u3',
                     'parameters': ['theta', 'phi', 'lambda'],
                     'qasm_def': 'u3(theta,phi,lambda) q { U(theta,phi,lambda) '
                                 'q; }'},
                 {   'coupling_map': [   [0],
                                         [1],
                                         [2],
                                         [3],
                                         [4],
                                         [5],
                                         [6],
                                         [7],
                                         [8],
                                         [9],
                                         [10],
                                         [11],
                                         [12],
                                         [13],
                                         [14],
                                         [15],
                                         [16],
                                         [17],
                                         [18],
                                         [19]],
                     'name': 'rz',
                     'parameters': ['theta'],
                     'qasm_def': 'gate rz(theta) q { U(0, 0, theta) q; }'},
                 {   'coupling_map': [   [0, 1],
                                         [1, 0],
                                         [0, 19],
                                         [19, 0],
                                         [0, 2],
                                         [2, 0],
                                         [0, 3],
                                         [3, 0],
                                         [1, 2],
                                         [2, 1],
                                         [1, 3],
                                         [3, 1],
                                         [1, 4],
                                         [4, 1],
                                         [2, 3],
                                         [3, 2],
                                         [2, 4],
                                         [4, 2],
                                         [3, 4],
                                         [4, 3],
                                         [4, 5],
                                         [5, 4],
                                         [5, 6],
                                         [6, 5],
                                         [5, 7],
                                         [7, 5],
                                         [5, 8],
                                         [8, 5],
                                         [6, 7],
                                         [7, 6],
                                         [6, 8],
                                         [8, 6],
                                         [6, 9],
                                         [9, 6],
                                         [7, 8],
                                         [8, 7],
                                         [7, 9],
                                         [9, 7],
                                         [8, 9],
                                         [9, 8],
                                         [9, 10],
                                         [10, 9],
                                         [10, 11],
                                         [11, 10],
                                         [10, 12],
                                         [12, 10],
                                         [10, 13],
                                         [13, 10],
                                         [11, 12],
                                         [12, 11],
                                         [11, 14],
                                         [14, 11],
                                         [11, 15],
                                         [15, 11],
                                         [12, 13],
                                         [13, 12],
                                         [12, 16],
                                         [16, 12],
                                         [13, 14],
                                         [14, 13],
                                         [13, 15],
                                         [15, 13],
                                         [14, 15],
                                         [15, 14],
                                         [14, 16],
                                         [16, 14],
                                         [15, 16],
                                         [16, 15],
                                         [16, 17],
                                         [17, 16],
                                         [17, 18],
                                         [18, 17],
                                         [17, 19],
                                         [19, 17],
                                         [18, 19],
                                         [19, 18]],
                     'name': 'cx',
                     'parameters': [],
                     'qasm_def': 'gate cx q1,q2 { CX q1,q2; }'}],
    'local': 'true',
    'max_shots': 9000,
    'memory': 'true',
    'n_qubits': 20,
    'open_pulse': 'false',
    'simulator': 'true'}
backend = AerSimulator(properties=BackendProperties.from_dict(prop_dict), configuration=QasmBackendConfiguration.from_dict(config_dict), basis_gates=['u1','u2','u3','rz','cx'])