# Generated by Django 5.0.3 on 2024-05-08 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fidelity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fidelity', models.FloatField()),
                ('circuit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.circuit')),
            ],
        ),
    ]
