# Generated by Django 5.0.3 on 2024-05-08 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_fidelity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fidelity',
        ),
    ]
