# Generated by Django 5.0.3 on 2024-05-08 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_fidelity'),
    ]

    operations = [
        migrations.AddField(
            model_name='circuit',
            name='fidelity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
